from pathlib import Path


ROOT_DIRECTORY = Path(__file__).parent.parent.resolve()
DATA_DIRECTORY = ROOT_DIRECTORY / "data"
KAGGLE_TMDB_MOVIES_DATASET_NAME = "tmdb-movies-dataset-2023-930k-movies.zip"
KAGGLE_TMDB_TVSHOWS_DATASET_NAME = "full-tmdb-tv-shows-dataset-2023-150k-shows.zip"
KAGGLE_TMDB_MOVIES_DATASET_PATH = DATA_DIRECTORY / KAGGLE_TMDB_MOVIES_DATASET_NAME
KAGGLE_TMDB_TVSHOWS_DATASET_PATH = DATA_DIRECTORY / KAGGLE_TMDB_TVSHOWS_DATASET_NAME
